# Description:
#   Mirroring the packages

name: MirrorExternals

on:
  push:
    branches:
    - master

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - name: mirror
        run: |
          cat /etc/os-release

