# Description:
#   Mirroring the packages

name: MirrorExternals

on:
  push:
    branches:
    - master

jobs:
  mirroring:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All the required packages are list here.
        PACKAGE_URL: 
          - https://gitlab.cern.ch/gaudi/Gaudi
          - https://github.com/key4hep/K4FWCore
    steps:
      - name: mirror
        run: |
          echo ${PACKAGE_URL}
          git clone ${PACKAGE_URL}
        env:
          PACKAGE_URL: ${{matrix.PACKAGE_URL}}

